# Generated by Django 3.1.7 on 2021-04-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='timenow',
        ),
        migrations.AlterField(
            model_name='dish',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
