# Generated by Django 3.1.7 on 2021-04-03 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210403_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='duration',
        ),
    ]
